QUOTES = [
    "Work hard, play harder",
    "Dunk on the crusties!",
    "The worst thing you can be is a crustomer",
    "Bath bombs? I'm more of a math bomb guy myself",
    "Do you ever read these?",
    "Binky bink bunk bunko buoy",
    "Slinky shink dink donk dunko bro",
    "You'll come up with something eventually, Batman...",
    "Holy Hamberders and Halibuts, Batman! I think the clapping of your cheeks is going to alert the Jonker!",
    "Can you help me find soap for my stinkys?",
    "Gone fishin, be back with Lush",
    "Dank bubble bars, my bubble star",
    "I lost the plot a while ago on this, didn't I?",
    "Just don't crash on the way (and on the way home avoiding that would be nice too)!",
    'Workin hard for the money! Go baby!',
    "Oh yeah! like the kool-aid guy, yanno?",
]